### ISSUE TITLE
Migration to YAML confuration system

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#1136]
The idea is to be able to use the YAML configuration feature with as little changes as possible to the current configuration files and `HardwareObjects`. As pointed out by both @elmjag  and @rhfogh  this is still a **breaking** change and it will very likely be necessary to make some of the changes described in the documentation above on your site.

The migration guide can be found here: 

     https://mxcubecore--1062.org.readthedocs.build/en/1062/dev/yaml_conf_migration.html

Its still possible to use both XML and YAML files for configuration and mix both, however some features for accessing configuration  (described  above) have been changed or deprecated.

This issue covers all discussions and issues that may arise once the `yaml` branch have been merged into `develop`

**Comment by HilbertCorsair** [comment]
Hi Marcus, Thank you for opening this issue!
I ran into some configuration isues regarding the tango channels. As an example for TangoMachineInfo my configuration is : 
```yaml
class: mxcubecore.HardwareObjects.TangoMachineInfo.TangoMachineInfo

#TangoMachineInfo expects get_property("parameters") and channels under "tango:" (see protocols_config).
#Channel name "current" is required (default in AbstractMachineInfo); it maps to machCurrent attribute here.
configuration:
  parameters: '["current", "machCurrent", "fillingMode", "operatorMessage0", "operatorMessage1", "operatorMessage2", "isBeamUsable", "temperatureExp", "transmission", "energy", "sampleTemp", "cryoJetIn", "scAutoRefill", "scOverflowAlarm", "scLowLevelAlarm"]'
  defaultFlux: 1e+12
  intensity:
#------------------------------------------

#Protocol section: setup_commands_channels() only processes tango/exporter/epics/sardana.
#Structure: device_name -> channels dict (channel name -> optional attribute, polling_period).
tango:
  "tango/device/address":
    channels:
      current:
        polling: 1000
      fillingMode:
        polling: 1000
      operatorMessage0:
        polling: 1000
      operatorMessage1:
        polling 1000
      operatorMessage2:
#----------------------------------------------------------
```
This throws an error when the get_channel("curent")  is called and the self.__channels object in the ComandContainer is empty. Channels are filled in CommandContainer.add_channel() only when setup_commands_channels() runs and finds protocol sections (tango, exporter, etc.) in the config dict it receives. Loking at the protocols_setup.py I think it is on the one hand trying to automaticly determine the ptotocole and on the other hand in the setup_comands_channels() https://github.com/mxcube/mxcubecore/blob/468091d90151bc0c73c2572002a123ec34f2f8da/mxcubecore/protocols_config.py#L177
The configuration channels dictionarry is in HO.config.tango but the channels are not further processed and are not available via get_channel_object("current")
Am I missing something or is this a bug that needs to be fixed?
