### ISSUE TITLE
Create a CITATION file

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#941]
See: <https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files>

**Comment by fabcor-maxiv** [comment]
For example, I pasted `https://doi.org/10.1107/S1600577519001267` into <https://cff-editor.mcrespo.me/> and it generated this (open "details" to read):

<details>

```yaml
cff-version: 1.2.0
title: '<i>MXCuBE2</i>: the dawn of <i>MXCuBE</i> Collaboration'
doi: 10.1107/s1600577519001267
message: If you use this software in your work, please cite it using the following metadata.
date-released: 2019-02-21
authors:
  - given-names: Marcus
    family-names: Oscarsson
  - given-names: Antonia
    family-names: Beteva
  - given-names: David
    family-names: Flot
  - given-names: Elspeth
    family-names: Gordon
  - given-names: Matias
    family-names: Guijarro
  - given-names: Gordon
    family-names: Leonard
  - given-names: Sean
    family-names: McSweeney
  - given-names: Stephanie
    family-names: Monaco
  - given-names: Christoph
    family-names: Mueller-Dieckmann
  - given-names: Max
    family-names: Nanao
  - given-names: Didier
    family-names: Nurizzo
  - given-names: Alexander N.
    family-names: Popov
  - given-names: David
    family-names: von Stetten
  - given-names: Olof
    family-names: Svensson
  - given-names: Vicente
    family-names: Rey-Bakaikoa
  - given-names: Idrissou
    family-names: Chado
  - given-names: Leonard M. G.
    family-names: Chavas
  - given-names: Laurent
    family-names: Gadea
  - given-names: Patrick
    family-names: Gourhant
  - given-names: Tatiana
    family-names: Isabet
  - given-names: Pierre
    family-names: Legrand
  - given-names: Martin
    family-names: Savko
  - given-names: Serena
    family-names: Sirigu
  - given-names: William
    family-names: Shepard
  - given-names: Andrew
    family-names: Thompson
  - given-names: Uwe
    family-names: Mueller
  - given-names: Jie
    family-names: Nan
  - given-names: Mikel
    family-names: Eguiraun
  - given-names: Fredrick
    family-names: Bolmsten
  - given-names: Alberto
    family-names: Nardella
  - given-names: Antonio
    family-names: Milàn-Otero
  - given-names: Marjolein
    family-names: Thunnissen
  - given-names: Michael
    family-names: Hellmig
  - given-names: Alexandra
    family-names: Kastner
  - given-names: Lukas
    family-names: Schmuckermaier
  - given-names: Martin
    family-names: Gerlach
  - given-names: Christian
    family-names: Feiler
  - given-names: Manfred S.
    family-names: Weiss
  - given-names: Matthew W.
    family-names: Bowler
  - given-names: Alexandre
    family-names: Gobbo
  - given-names: Gergely
    family-names: Papp
  - given-names: Jeremy
    family-names: Sinoir
  - given-names: Andrew A.
    family-names: McCarthy
  - given-names: Ivars
    family-names: Karpics
  - given-names: Marina
    family-names: Nikolova
  - given-names: Gleb
    family-names: Bourenkov
  - given-names: Thomas
    family-names: Schneider
  - given-names: Jordi
    family-names: Andreu
  - given-names: Guifré
    family-names: Cuní
  - given-names: Judith
    family-names: Juanhuix
  - given-names: Roeland
    family-names: Boer
  - given-names: Rasmus
    family-names: Fogh
  - given-names: Peter
    family-names: Keller
  - given-names: Claus
    family-names: Flensburg
  - given-names: Wlodek
    family-names: Paciorek
  - given-names: Clemens
    family-names: Vonrhein
  - given-names: Gerard
    family-names: Bricogne
  - given-names: Daniele
    family-names: de Sanctis
abstract: 'This repository contains the source code of the paper <i>MXCuBE2</i>: the dawn of <i>MXCuBE</i> Collaboration by Marcus Oscarsson, Antonia Beteva, David Flot, Elspeth Gordon, Matias Guijarro, Gordon Leonard, Sean McSweeney, Stephanie Monaco, Christoph Mueller-Dieckmann, Max Nanao, Didier Nurizzo, Alexander N. Popov, David von Stetten, Olof Svensson, Vicente Rey-Bakaikoa, Idrissou Chado, Leonard M. G. Chavas, Laurent Gadea, Patrick Gourhant, Tatiana Isabet, Pierre Legrand, Martin Savko, Serena Sirigu, William Shepard, Andrew Thompson, Uwe Mueller, Jie Nan, Mikel Eguiraun, Fredrick Bolmsten, Alberto Nardella, Antonio Milàn-Otero, Marjolein Thunnissen, Michael Hellmig, Alexandra Kastner, Lukas Schmuckermaier, Martin Gerlach, Christian Feiler, Manfred S. Weiss, Matthew W. Bowler, Alexandre Gobbo, Gergely Papp, Jeremy Sinoir, Andrew A. McCarthy, Ivars Karpics, Marina Nikolova, Gleb Bourenkov, Thomas Schneider, Jordi Andreu, Guifré Cuní, Judith Juanhuix, Roeland Boer, Rasmus Fogh, Peter Keller, Claus Flensburg, Wlodek Paciorek, Clemens Vonrhein, Gerard Bricogne and Daniele de Sanctis, from J Synchrotron Radiat'
version: 1.0.0
```

</details>

**Comment by fabcor-maxiv** [comment]
Pasting this other DOI URL <https://doi.org/10.1107/s0909049510020005> into <https://cff-editor.mcrespo.me/> delivers (open "details" to read):

<details>

```yaml
cff-version: 1.2.0
title: '<i>MxCuBE</i>: a synchrotron beamline control environment customized for macromolecular crystallography experiments'
doi: 10.1107/s0909049510020005
message: If you use this software in your work, please cite it using the following metadata.
date-released: 2010-07-11
authors:
  - given-names: José
    family-names: Gabadinho
  - given-names: Antonia
    family-names: Beteva
  - given-names: Matias
    family-names: Guijarro
  - given-names: Vicente
    family-names: Rey-Bakaikoa
  - given-names: Darren
    family-names: Spruce
  - given-names: Matthew W.
    family-names: Bowler
  - given-names: Sandor
    family-names: Brockhauser
  - given-names: David
    family-names: Flot
  - given-names: Elspeth J.
    family-names: Gordon
  - given-names: David R.
    family-names: Hall
  - given-names: Bernard
    family-names: Lavault
  - given-names: Andrew A.
    family-names: McCarthy
  - given-names: Joanne
    family-names: McCarthy
  - given-names: Edward
    family-names: Mitchell
  - given-names: Stéphanie
    family-names: Monaco
  - given-names: Christoph
    family-names: Mueller-Dieckmann
  - given-names: Didier
    family-names: Nurizzo
  - given-names: Raimond B. G.
    family-names: Ravelli
  - given-names: Xavier
    family-names: Thibault
  - given-names: Martin A.
    family-names: Walsh
  - given-names: Gordon A.
    family-names: Leonard
  - given-names: Sean M.
    family-names: McSweeney
abstract: 'This repository contains the source code of the paper <i>MxCuBE</i>: a synchrotron beamline control environment customized for macromolecular crystallography experiments by José Gabadinho, Antonia Beteva, Matias Guijarro, Vicente Rey-Bakaikoa, Darren Spruce, Matthew W. Bowler, Sandor Brockhauser, David Flot, Elspeth J. Gordon, David R. Hall, Bernard Lavault, Andrew A. McCarthy, Joanne McCarthy, Edward Mitchell, Stéphanie Monaco, Christoph Mueller-Dieckmann, Didier Nurizzo, Raimond B. G. Ravelli, Xavier Thibault, Martin A. Walsh, Gordon A. Leonard and Sean M. McSweeney, from J Synchrotron Radiat'
version: 1.0.0
```

</details>
